
- include: install-icingaweb2-redhat.yml
  when: ansible_os_family == "RedHat"

- include: install-icingaweb2-debian.yml
  when: ansible_os_family == "Debian"

- include: setup-phppool.yml
  when: icingaweb2_with_php_fpm

- name: Setup icingaweb2
  include: configure-icingaweb2.yml
